services:
    # リバースプロキシけんWeサーバ
    nginx:
        hostname: nginx
        image: nginx:latest
        ports:
            - 8943:8443
        restart: always
        tty: true
        volumes:
            - ./nginx/configs:/etc/nginx/conf.d/
            - ./nginx/keys:/etc/nginx/keys
            - ./nginx/statics:/etc/nginx/static/statics
    
    # 認証用コンテナ
    auth:
        hostname: auth
        image: mattuu0/authbase-auth:0.2.2
        env_file:
            - ./openssl/jwtKeys/private.env
            - ./config/auth.env
        volumes:
            - ./auth/src:/root/src
            - ./auth/icons:/assets/icons
        restart: always
    
    # ユーザーコンテナ
    user:
        hostname: user
        build:
            context: ./containers/user
            dockerfile: Dockerfile
            target: Develop
        tty: true
        env_file:
            - ./openssl/jwtKeys/public.env
            - ./config/user.env
        volumes:
            - ./containers/user/src:/root/src
        restart: always
        depends_on:
            auth:
                condition: service_started
    
    # ゲームコンテナ
    game:
        hostname: game
        build:
            context: ./containers/game
            dockerfile: Dockerfile
            target: Develop
        tty: true
        env_file:
            - ./openssl/jwtKeys/public.env
            - ./config/game.env
        volumes:
            - ./containers/game/src:/root/src
        restart: always
        depends_on:
            auth:
                condition: service_started
    
    # ゲームの核となるコンテナ
    gcore:
        hostname: gcore
        build:
            context: ./containers/gcore
            dockerfile: Dockerfile
            target: Develop
        tty: true
        env_file:
            - ./openssl/jwtKeys/public.env
            - ./config/gcore.env
        volumes:
            - ./containers/gcore/src:/root/src
        restart: always
        depends_on:
            auth:
                condition: service_started

    # データベース
    mysql:
        hostname: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            TZ: Asia/Tokyo
        volumes:
            - dbdata:/var/lib/mysql
            - ./database/my.cnf:/etc/mysql/conf.d/my.cnf
            - ./database/script/init.sql:/docker-entrypoint-initdb.d/init.sql 
    redis:
        hostname: redis
        image: redis:latest
        restart: always
        ports:
            - 16379:6379
volumes:
    dbdata: