@base_url = https://localhost:8943/game

@user_id = userid-79541130-3275-4b90-8677-01323045aca5

@circle_id =4535e17b-b38c-4449-9902-10861ee3b49b

@game_id = gameid-413a287b-213c-414f-a287-c1397db8f9bf

# test
GET {{base_url}}/

### ランキング取得
GET {{base_url}}/ranking/personal/{{user_id}}
### ランキングTOP10
GET {{base_url}}/ranking/top/{{game_id}}
UserID: userid-79541130-3275-4b90-8677-01323045aca5

### 上位3位の円を取得する
GET {{base_url}}/ranking/top/{{game_id}}
UserID: userid-79541130-3275-4b90-8677-01323045aca5

### 円の詳細取得
GET {{base_url}}/circle/{{circle_id}}

### 終了済みゲーム一覧
GET {{base_url}}/endgame/{{user_id}}

###   開催中のゲーム一覧取得
GET {{base_url}}/joingame/{{user_id}}

### ゲームに参加するエンドポイント
POST {{base_url}}/join
UserID: userid-e3abf90d-4bcf-4c3b-bbde-37694b1611b3
GameID: gameid-996e5916-28b7-4222-ad5c-b332c1f892ec
Content-Type: application/json

### 開始済みのゲーム一覧を取得する
GET {{base_url}}/startedgame 
UserID: userid-79541130-3275-4b90-8677-01323045aca5