@base_url = https://localhost:8943/game
# @base_url = https://rihlar-stage.kokomeow.com/game

@user_id = userid-79541130-3275-4b90-8677-01323045aca5

@circle_id = circle-548d4276-552b-404b-8c28-964281fd7f3b

# @game_id = gameid-413a287b-213c-414f-a287-c1397db8f9bf
@game_id = gameid-413a287b-213c-414f-a287-c1397db8f9bf

@image_circle_id = circle-548d4276-552b-404b-8c28-964281fd7f3b

@token = eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTQ4ODk1ODgsImxhYmVscyI6W10sInByb3ZDb2RlIjoiZ29vZ2xlIiwicHJvdlVpZCI6IjExMDg3MTY0NTY2MjI0MTc5NjA1OSIsInVzZXJJRCI6Ijg2NWZiYzI1LWRjMzAtNGI2OS1hZjlkLTkxY2IxMmJkNGZkZCJ9.Almm9F9w8Iu9hpA5vQTX5mk0-9jr1BZqrJU-kE-jCIIUboGTOSKppgvlp5iu4nxn0lK3fAwnw96EqrugXva5Dg

# test
GET {{base_url}}/

### ランキング取得
GET {{base_url}}/ranking/personal/{{user_id}}
### ランキングTOP10
GET {{base_url}}/ranking/top10/{{game_id}}
# UserID: userid-79541130-3275-4b90-8677-01323045aca5
Authorization: {{token}}

### ランキングTOP10 個人用
GET {{base_url}}/ranking/solo/top10/{{game_id}}
# UserID: userid-79541130-3275-4b90-8677-01323045aca5
Authorization: {{token}}

### 上位3位の円を取得する
GET {{base_url}}/ranking/top/{{game_id}}
# UserID: userid-79541130-3275-4b90-8677-01323045aca5
Authorization: {{token}}

### 円に画像をアップロードするエンドポイント
POST {{base_url}}/circle/image/upload
Content-Type: multipart/form-data; boundary=boundary
CircleID: {{circle_id}}
# UserID: {{user_id}}

--boundary
Content-Disposition: form-data; name="image"; filename="image.png"
Content-Type: image/png

< ./containers/game/src/assets/circle-images/umeda_image.png

--boundary

### 円のリストを取得
GET {{base_url}}/image/list
# UserID: {{user_id}}
Authorization: {{token}}

### 円の詳細取得
GET {{base_url}}/circle/{{circle_id}}

### 円の画像取得
GET  {{base_url}}/circle/image/{{image_circle_id}}

### 終了済みゲーム一覧
GET {{base_url}}/endgame/{{user_id}}

###   開催中のゲーム一覧取得
GET {{base_url}}/joingame/{{user_id}}

### ゲームに参加するエンドポイント
POST {{base_url}}/join
# UserID: userid-e3abf90d-4bcf-4c3b-bbde-37694b1611b3
Authorization: {{token}}
GameID: {{game_id}}
Content-Type: application/json

### 開始済みのゲーム一覧を取得する
GET {{base_url}}/startedgame 
UserID: userid-79541130-3275-4b90-8677-01323045aca5

### 開始済みのゲーム一覧を取得する
GET {{base_url}}/allgames
Authorization: {{token}}

### アイテム詳細取得
GET {{base_url}}/item
ItemID: item-26164e99-790e-429f-95df-8008eb34d628

### アイテムボックス取得
GET {{base_url}}/item/box
UserID: user-e3abf90d-4bcf-4c3b-bbde-37694b1611b3

### ガチャ取得
GET {{base_url}}/item/gacha
UserID: userid-e3abf90d-4bcf-4c3b-bbde-37694b1611b3

