@base_url = https://localhost:8943/game

@user_id = e3abf90d-4bcf-4c3b-bbde-37694b1611b3

@circle_id =4535e17b-b38c-4449-9902-10861ee3b49b


# test
GET {{base_url}}/

### ランキング取得
GET {{base_url}}/ranking/personal/{{user_id}}

### 円の詳細取得
GET {{base_url}}/circle/{{circle_id}}

### 終了済みゲーム一覧
GET {{base_url}}/endgame/{{user_id}}

### 参加している全てのゲーム一覧取得
GET {{base_url}}/joingame/{{user_id}}
