# @base_url = https://rihlar-test.kokomeow.com/gcore
@base_url = https://localhost:8943/gcore

### 関西
POST {{base_url}}/report/movement HTTP/1.1
UserID : userid-79541130-3275-4b90-8677-01323045aca5
Content-Type: application/json

{    "latitude": 34.70649578495347,
    "longitude": 135.50326868815958,
    "steps": 10
}

### 東京 (リージョン以外 ユーザー1)
POST {{base_url}}/report/movement HTTP/1.1
UserID : userid-8a5fafff-0b2e-4f2b-b011-da21a5a724cd
Content-Type: application/json

{
    "latitude": 35.7365646305852,
    "longitude": 139.80954685258914,
    "steps": 3000
}

### 東京 (リージョン以外 ユーザー2)
POST {{base_url}}/report/movement HTTP/1.1
UserID : userid-79541130-3275-4b90-8677-01323045aca5
Content-Type: application/json

{
    "latitude": 35.7365646305852,
    "longitude": 139.80954685258914,
    "steps": 10
}

### 東京 ユーザー 円を作成
POST {{base_url}}/create/circle HTTP/1.1
# UserID : userid-8a5fafff-0b2e-4f2b-b011-da21a5a724cd
Authorization: eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTMyNDE5MDksImxhYmVscyI6W10sInByb3ZDb2RlIjoiZ29vZ2xlIiwicHJvdlVpZCI6IjExMDg3MTY0NTY2MjI0MTc5NjA1OSIsInVzZXJJRCI6Ijc1ZTZmMDc5LWVlOTEtNDNkMC04ODJmLWFmZGU4ZjI4MzBjZCJ9.EPH07DrZYs1ixpJ57AWQzrIxulRY3apObLHZBcP-b3i8JYfqKvXT3luJYKharkOElthcdfBh_9W43VyOc4_lBA
Content-Type: application/json

{
    "latitude": 34.98652833029375,
    "longitude": 135.3793990772704,
    "steps": 10000,
    "theme": "動物"
}

### 東京 ユーザー2 円を作成
POST {{base_url}}/create/circle HTTP/1.1
# UserID : userid-79541130-3275-4b90-8677-01323045aca5
Content-Type: application/json

{
    "latitude": 35.7365646305852,
    "longitude": 139.80954685258914,
    "steps": 10,
    "theme": "zoo"
}

### 歩いたデータを取得する
GET {{base_url}}/get/movement HTTP/1.1
UserID : userid-79541130-3275-4b90-8677-01323045aca5
GameID : gameid-413a287b-213c-414f-a287-c1397db8f9bf
Content-Type: application/json

### ランキングを取得する
GET {{base_url}}/get/top HTTP/1.1
UserID : userid-79541130-3275-4b90-8677-01323045aca5
GameID : gameid-413a287b-213c-414f-a287-c1397db8f9bf
Content-Type: application/json