name: Build Game Container

on:
  push:
    branches: [ "develop" ]
    paths:
      - 'containers/game/**'
      - '.github/workflows/**'
jobs:
  build-game:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - id: lower-repo
        shell: pwsh
        run: |
          "::set-output name=repository::$($env:GITHUB_REPOSITORY.ToLowerInvariant())"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          context: ./containers/game
          file: ./containers/game/Dockerfile
          tags: ghcr.io/${{ steps.lower-repo.outputs.repository }}/rihlar-game:${{ github.sha }}, ghcr.io/${{ steps.lower-repo.outputs.repository }}/rihlar-game:latest